pool:
  vmImage: macOS-latest

steps:
- script: sw_vers
  displayName: 'Check macOS version'
- script: curl http://ipv4.download.thinkbroadband.com/512MB.zip --output 512MB.zip
  displayName: 'Download 500mb file'
- script: mkfile -n 1g ~/Desktop/LargeTestFile
  displayName: 'Create 1G file'
  
