pool:
  vmImage: ubuntu-latest

steps:
- script: cat /etc/os-release
  displayName: 'Check ubuntu version'
- script: curl http://ipv4.download.thinkbroadband.com/512MB.zip --output 512MB.zip
  displayName: 'Download 500mb file'
- script: fallocate -l 1G testfile.txt 
  displayName: 'Create 1G file'
  
