version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: 'Check ubuntu version'
          command: cat /etc/os-release
      - run:
          name: Download 500mb file
          command: curl http://ipv4.download.thinkbroadband.com/512MB.zip --output 512MB.zip
      - run:
          name: Create 1G file
          command: fallocate -l 1G testfile.txt 
