version: 2.1

jobs:
  build:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run:
          name: 'Check macOS version'
          command: sw_vers
      - run:
          name: Download 500mb file
          command: curl http://ipv4.download.thinkbroadband.com/512MB.zip --output 512MB.zip
      - run:
          name: Create 1G file
          command: mkfile -n 1g ~/Desktop/LargeTestFile
